### PR TITLE
feat: support btc psbt

### PR DESCRIPTION
**Pull request by fbwoolf**
This PR adds a `psbtRequest` method to the `StacksProvider`.

### CODE REVIEW

**Comment by markmhx** [comment]
In support of https://github.com/hirosystems/stacks-wallet-web/issues/3310

**Comment by fbwoolf** [comment]
@janniks I have forgotten the preferred way to work with the Connect repo, what is the best way to make this branch/pr available for others to test via npm rather than yalc locally?

**Comment by janniks** [comment]
The PRs are automatically released under an alpha version to npm, make sure to use `--save-exact` when installing since sometimes versions can conflict.

**Review by janniks — CHANGES_REQUESTED** [review]
Looking good! 🚀
Some minor notes, not really code-changes -- should we roll this out as "experimental" at first for testing with the first few/known apps?

**Comment by fbwoolf** [comment]
@janniks @kyranjamie hoping to get an approval to merge this today if possible?

**Review by janniks — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

**Comment by radicleart** [comment]
@fbwoolf exciting stuff - thanks you! 

This will be in 7.2.2 of stacks/connect ? Do you know when this will be available ?

**Pull request merged**
